#!/bin/bash
# Create one low-impact, sequential backup job for many MariaDB/PostgreSQL DBs.

BASE_DIR="/opt/shieldpress"
source "$BASE_DIR/core/paths.sh"

pause(){ echo ""; read -rp "Press Enter..."; }
valid_number(){ [[ "$1" =~ ^[0-9]+$ ]] && [ "$1" -ge "$2" ] && [ "$1" -le "$3" ]; }

clear
echo "===================================================="
echo "             AUTO BACKUP FULL DB (BATCH)"
echo "===================================================="
echo "  One job backs up databases one at a time."
echo "  It uses a lock, nice/ionice and a delay between dumps."
echo ""

declare -a ENGINES DBS PATHS LABELS
index=1
add_database(){
    local engine="$1" db="$2" domain_path="$3" label="$4"
    ENGINES[$index]="$engine"; DBS[$index]="$db"; PATHS[$index]="$domain_path"; LABELS[$index]="$label"
    printf '  %2d) %-9s %-30s %s\n' "$index" "$engine" "$db" "$label"
    ((index++))
}

# List site databases first; this supplies credentials and stores each archive with its site.
declare -A SEEN
for env in "$DOMAINS_ROOT"/*/config/domain.env; do
    [ -f "$env" ] || continue
    db=$(grep '^DB_NAME=' "$env" | cut -d= -f2- | tr -d '[:space:]')
    engine=$(grep '^DB_CONNECTION=' "$env" | cut -d= -f2- | tr -d '[:space:]')
    domain=$(grep '^DOMAIN=' "$env" | cut -d= -f2- | tr -d '[:space:]')
    case "$engine" in mysql|mariadb) engine=mysql ;; pgsql|postgres|postgresql) engine=pgsql ;; *) continue ;; esac
    [ -n "$db" ] || continue
    key="$engine:$db"; [ -n "${SEEN[$key]}" ] && continue; SEEN[$key]=1
    add_database "$engine" "$db" "$(dirname "$(dirname "$env")")" "${domain:-linked site}"
done

# Also include databases not linked to a ShieldPress domain.
if command -v mysql >/dev/null 2>&1; then
    while IFS= read -r db; do
        [ -z "$db" ] && continue
        key="mysql:$db"; [ -n "${SEEN[$key]}" ] && continue; SEEN[$key]=1
        add_database mysql "$db" "" "standalone"
    done < <(mysql -N -e 'SHOW DATABASES;' 2>/dev/null | grep -Ev '^(information_schema|performance_schema|mysql|sys)$')
fi
if command -v psql >/dev/null 2>&1; then
    while IFS= read -r db; do
        [ -z "$db" ] && continue
        key="pgsql:$db"; [ -n "${SEEN[$key]}" ] && continue; SEEN[$key]=1
        add_database pgsql "$db" "" "standalone"
    done < <(runuser -u postgres -- psql -tAc "SELECT datname FROM pg_database WHERE datistemplate=false AND datname <> 'postgres'" 2>/dev/null)
fi

[ "$index" -gt 1 ] || { echo "No supported databases found."; pause; exit 1; }
echo "----------------------------------------------------"
read -rp "Choose numbers (e.g. 1,3-5) or 'all': " selected

declare -a PICKED
if [ "$selected" = "all" ]; then
    for ((n=1; n<index; n++)); do PICKED+=("$n"); done
else
    IFS=',' read -ra pieces <<< "$selected"
    for piece in "${pieces[@]}"; do
        if [[ "$piece" =~ ^([0-9]+)-([0-9]+)$ ]]; then
            for ((n=${BASH_REMATCH[1]}; n<=${BASH_REMATCH[2]}; n++)); do [ -n "${DBS[$n]}" && PICKED+=("$n"); done
        elif [[ "$piece" =~ ^[0-9]+$ ]] && [ -n "${DBS[$piece]}" ]; then PICKED+=("$piece"); fi
    done
fi
[ "${#PICKED[@]}" -gt 0 ] || { echo "No valid databases selected."; pause; exit 1; }

while ! valid_number "$RETENTION" 1 60; do read -rp "Keep how many backups per database (1-60): " RETENTION; done
while ! valid_number "$HOUR" 0 23; do read -rp "Start hour (0-23): " HOUR; done
while ! valid_number "$DELAY" 5 3600; do read -rp "Seconds to wait between databases (5-3600): " DELAY; done
echo "1) Daily   2) Weekly   3) Monthly"; read -rp "Frequency: " freq
case "$freq" in
  1) CRON_TIME="0 $HOUR * * *" ;;
  2) while ! valid_number "$dow" 0 6; do read -rp "Day of week (0=Sun): " dow; done; CRON_TIME="0 $HOUR * * $dow" ;;
  3) while ! valid_number "$dom" 1 28; do read -rp "Day of month (1-28): " dom; done; CRON_TIME="0 $HOUR $dom * *" ;;
  *) echo "Invalid frequency."; pause; exit 1 ;;
esac

mkdir -p "$BASE_DIR/config/auto-backup"
AUTO_SCRIPT="$BASE_DIR/config/auto-backup/auto-backup-full-db-batch.sh"
{
cat <<'RUNNER'
#!/bin/bash
# Generated by ShieldPress. Database dumps are deliberately sequential.
set -o pipefail
BASE_DIR="/opt/shieldpress"
source "$BASE_DIR/core/paths.sh"
RUN_LOG_FILE="$LOG_DIR/auto-backup.log"
LOCK_FILE="$DATA_DIR/auto-backup-full-db-batch.lock"
exec 9>"$LOCK_FILE"
flock -n 9 || { echo "$(date '+%F %T') | SKIP: full DB batch is already running" >> "$RUN_LOG_FILE"; exit 0; }

value_from_env(){ grep "^$2=" "$1/config/domain.env" 2>/dev/null | head -n1 | cut -d= -f2-; }
backup_one(){
    local engine="$1" db="$2" domain_path="$3" retention="$4" date file backup_dir db_user db_pass domain status
    if [ -n "$domain_path" ] && [ -f "$domain_path/config/domain.env" ]; then
        db_user=$(value_from_env "$domain_path" DB_USER); db_pass=$(value_from_env "$domain_path" DB_PASS); domain=$(value_from_env "$domain_path" DOMAIN)
        backup_dir="$domain_path/backup/db"
    else
        db_user=""; db_pass=""; domain="$db"; backup_dir="$BACKUP_GLOBAL_DIR/standalone-db"
    fi
    mkdir -p "$backup_dir"
    date=$(date +%F_%H-%M-%S); file="$backup_dir/${db}_${date}.sql.gz"; status=1
    case "$engine" in
      mysql)
        if [ -n "$db_user" ]; then nice -n 15 ionice -c2 -n7 mysqldump --single-transaction --quick --routines --triggers --events --hex-blob -u "$db_user" -p"$db_pass" "$db" | gzip > "$file"
        else nice -n 15 ionice -c2 -n7 mysqldump --single-transaction --quick --routines --triggers --events --hex-blob "$db" | gzip > "$file"; fi
        pipe_status=("${PIPESTATUS[@]}"); status=0; for code in "${pipe_status[@]}"; do [ "$code" -eq 0 ] || status=1; done ;;
      pgsql)
        if [ -n "$db_user" ] && [ -n "$db_pass" ]; then PGPASSWORD="$db_pass" nice -n 15 ionice -c2 -n7 pg_dump -h 127.0.0.1 -U "$db_user" -d "$db" --no-owner --no-privileges | gzip > "$file"
        else nice -n 15 ionice -c2 -n7 runuser -u postgres -- pg_dump -d "$db" --no-owner --no-privileges | gzip > "$file"; fi
        pipe_status=("${PIPESTATUS[@]}"); status=0; for code in "${pipe_status[@]}"; do [ "$code" -eq 0 ] || status=1; done ;;
    esac
    if [ "$status" -eq 0 ] && gzip -t "$file" 2>/dev/null; then
        echo "$(date '+%F %T') | SUCCESS: batch DB $domain ($engine/$db): $file" >> "$RUN_LOG_FILE"
        find "$backup_dir" -maxdepth 1 -type f -name "${db}_*.sql.gz" -printf '%T@ %p\n' | sort -nr | tail -n +$((retention+1)) | cut -d' ' -f2- | xargs -r rm -f
        source "$BASE_DIR/modules/backup/_backup_helper.sh"; remote_upload_backup "$file" "db"
    else
        echo "$(date '+%F %T') | FAILED: batch DB $domain ($engine/$db)" >> "$RUN_LOG_FILE"; rm -f "$file"
        source "$BASE_DIR/modules/backup/_backup_helper.sh"; shieldpress_notify_event "backup_fail" "Batch database backup failed" "$domain ($engine/$db)"
    fi
}
RUNNER
printf 'RETENTION=%q\nDELAY=%q\n' "$RETENTION" "$DELAY"
printf 'JOBS=(\n'
for n in "${PICKED[@]}"; do printf '  %q\n' "${ENGINES[$n]}|${DBS[$n]}|${PATHS[$n]}"; done
cat <<'RUNNER'
)
for job in "${JOBS[@]}"; do
    IFS='|' read -r engine db domain_path <<< "$job"
    backup_one "$engine" "$db" "$domain_path" "$RETENTION"
    sleep "$DELAY"
done
RUNNER
} > "$AUTO_SCRIPT"
chmod 700 "$AUTO_SCRIPT"
(crontab -l 2>/dev/null | grep -vF "$AUTO_SCRIPT"; echo "$CRON_TIME $AUTO_SCRIPT") | crontab -
echo ""; echo "[OK] Scheduled ${#PICKED[@]} databases sequentially ($CRON_TIME)."; echo "     Script: $AUTO_SCRIPT"; pause
